baseURL: "https://blog.pietrodn.com/"
title: "Pietro's Blog"
paginate: 10
theme: papermod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics: UA-123-45

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production
  title: "Pietro's Blog"
  description: "Personal portfolio and blog of Pietro De Nicolao"
  keywords: [Blog, Portfolio]
  author: "Pietro De Nicolao"
  images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: "2006-01-06"
  defaultTheme: auto
  disableThemeToggle: false
  math: true # enable KaTeX: https://github.com/adityatelange/hugo-PaperMod/blob/exampleSite/content/posts/math-typesetting.md

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  label:
    text: "Home"
    icon: /apple-touch-icon.png
    iconHeight: 35

  # profile-mode
  profileMode:
    enabled: true # needs to be explicitly set
    title: "Pietro De Nicolao"
    subtitle: ""
    imageUrl: "/images/PD-portrait.jpeg"
    imageWidth: 200
    imageHeight: 200
    imageTitle: my image
    buttons:
      - name: Posts
        url: posts
      - name: About
        url: about

  socialIcons:
    - name: rss
      url: "/index.xml"
    - name: facebook
      url: "https://facebook.com/pietrodn"
    - name: twitter
      url: "https://twitter.com/pietrodn"
    - name: linkedin
      url: "https://www.linkedin.com/in/pietrodn/"
    - name: stackoverflow
      url: "https://stackoverflow.com/users/1792585/pietrodn"
    - name: github
      url: "https://github.com/pietrodn"
    - name: instagram
      url: "https://instagram.com/power.pete.93"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

menu:
  main:
    - identifier: about
      name: About
      url: /about/
      weight: 10
    - identifier: archives
      name: Posts
      url: /posts/
      weight: 20
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 30
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
# pygmentsUseClasses: true
# markup:
#     highlight:
#         # anchorLineNos: true
#         codeFences: true
#         guessSyntax: true
#         lineNos: true
#         style: monokai


outputs:
    home:
        - HTML
        - RSS
        - JSON # necessary for search

copyright: '© 2021 Pietro De Nicolao. Licensed under the [CC-BY 4.0](https://creativecommons.org/licenses/by/4.0/) license.'

taxonomies:
  tag: tags

privacy:
  disqus:
    disable: true
  googleAnalytics:
    disable: true
  instagram:
    disable: true
  twitter:
    disable: false
    enableDNT: true
    simple: false
  vimeo:
    disable: true
  youtube:
    disable: false
    privacyEnhanced: true

markup:
  goldmark:
    renderer:
      unsafe: true
